web/app/patient/forms.py
# import necessary packages
from wtforms import Form, StringField, PasswordField, validators, SelectField
from flask import session
from wtforms.validators import ValidationError
from wtforms.validators import ValidationError
from app.patient.patient_services import PatientService
from app.clerk.clerk_services import ClerkService
from app.doctor.doctor_services import DoctorService
from init import session

# define the reg form model
class RegForm(Form):
    """
    patient register form
    """
    username = StringField('username', validators=[
        validators.DataRequired(),
        validators.Length(min=4, max=25)
    ])

    email = StringField('email', validators=[
        validators.DataRequired(),
        validators.Email()
    ])

    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])

    confirm = PasswordField('Repeat Password')

# define the login form model
class LoginForm(Form):
    """
    patient sign in form
    """
    username = StringField('username', validators=[
        validators.DataRequired()
    ])

    password = PasswordField('password', validators=[
        validators.DataRequired()
    ])

    role = SelectField('role', choices=[('1', 'Patient'), ('2', 'Doctor'), ('3', 'Clerk')], validators=[
        validators.DataRequired()
    ])

    # validate username and password
    def validate_username(form, field):
        username = field.data
        password = form.password.data
        role = form.role.data
        if role == '1':
            ps = PatientService()
            payload = {
                'patient': {
                    'username': username,
                    'password': password
                }
            }
            res, data = ps.login(payload)
            
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Patient'
                session['User'] = d
        elif role == '2':
            ds = DoctorService()
            payload = {
                'doctor': {
                    'username': username,
                    'password': password
                }
            }
            res, data = ds.login(payload)
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Doctor'
                session['User'] = d
        elif role == '3':
            cs = ClerkService()
            payload = {
                'clerk': {
                    'username': username,
                    'password': password
                }
            }
            res, data = cs.login(payload)
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Clerk'
                session['User'] = d

# define form for account
class UpdateForm(Form):
    """
    patient update account form
    """
    username = StringField('Username', validators=[
        validators.DataRequired()
    ])

    sex = SelectField('Sex', choices=[('1', 'Male'), ('2', 'Female')], validators=[
        validators.DataRequired()
    ])

    name = StringField('Name', validators=[
        validators.DataRequired()
    ])

    birthday = StringField('Birthday', validators=[
        validators.DataRequired()
    ])

    phone = StringField('Phone No', validators=[
        validators.DataRequired()
    ])

    email = StringField('Email', validators=[
        validators.DataRequired()
    ])

    age = StringField('Age', validators=[
        validators.DataRequired()
    ])

web/app/patient/views.py
# append path
import sys
import os
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

# import necessary packages
from flask import Blueprint, Flask, render_template, session, redirect, url_for, request, jsonify, make_response
from forms import RegForm, UpdateForm
from app.patient.patient_services import PatientService
from app.doctor.doctor_services import DoctorService
import time
from init import app

# create blueprint object
patient_blueprint = Blueprint(
    'patient', 
    __name__,
    template_folder='../../templates',
    url_prefix='/patient'
)

# setting
def patientSetting():

    """
    menu setting
    :return:  object
    """
    settings = {
        'title' : 'Patient',
        'menu' : {
            'Appointment' : {
                'icon' : 'mdi mdi-calendar-clock',
                'new' : True,
                'url' : url_for('patient.makeAppointment'),
            },
            'Account' : {
                'icon' : 'mdi mdi-account',
                'url' : url_for('patient.account'),
            }
        }
    }
    return settings

@patient_blueprint.route('/index')
def index():
    """
    index
    :return: default page
    """
    return redirect(url_for('patient.account'))

@patient_blueprint.route('/account', methods=['GET', 'POST'])
def account():
    """
    show account page
    :return: render page
    """
    form = UpdateForm(request.form)
    if request.method == 'GET':
        form.username.data = session['User']['username']
        form.name.data = session['User']['name']
        form.email.data = session['User']['email']
        form.age.data = session['User']['age']
        form.sex.data = session['User']['sex']
        form.birthday.data = session['User']['birthday']
        form.phone.data = session['User']['phone']
    if request.method == 'POST' and form.validate():
        # update data of patient
        ps = PatientService()
        payload = {
            'patient': form.data
        }
        res, data = ps.update(payload)
        if res:
            return render_template('patient/account.html', **patientSetting(), form = form)
    return render_template('patient/account.html', **patientSetting(), form = form)

# make appointment
@patient_blueprint.route('/make_appointment')
def makeAppointment():
    """
    make an appointment
    :return: render page
    """
    ds = DoctorService()
    res, doctors = ds.getAll()
    data = doctors['data']
    return render_template('patient/calendar.html', **patientSetting(), doctors=data)

# get doctor
@patient_blueprint.route('/get_doctor/<doctor_id>')
def getDoctor(doctor_id):
    """
    get one doctor
    :param doctor_id: doctor id
    :return: json
    """
    ds = DoctorService()
    res, data = ds.getDoctorById(doctor_id)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Fetched!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# @patient_blueprint.route('/delete_appointment')
# def deleteAppointment():
#     return render_template('patient/calendar.html', **patientSetting())

# register a patient
@patient_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    register a patient
    :return:render page
    """
    form = RegForm(request.form)
    if request.method == 'POST' and form.validate():
        # pass the validation, request API
        ps = PatientService()
        payload = {
            'patient' : {
                'username': form.username.data,
                'password': form.password.data,
                'email': form.email.data,
                'created_at': time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            }
        }
        res, data = ps.register(payload)
        if res:
            return redirect(url_for('login'))
    return render_template('patient/register.html', form=form)

# get events by doctorid
@patient_blueprint.route('/get_events/<doctor_id>', methods=['GET'])
def getEventsByDoctorId(doctor_id):
    """
    get all events by doctor id
    :param doctor_id: doctor id
    :return: json
    """
    ps = PatientService()
    res, data = ps.getEventsByDoctorId(doctor_id)
    if res and data is not None:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Fetched!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# get events by doctorid
@patient_blueprint.route('/update_events', methods=['POST'])
def updateEventsByDoctorId():
    """
    update events by doctor id
    :return: json
    """
    doctorId = request.form.getlist('doctor_id')[0]
    eventId = request.form.getlist('event_id')[0]
    delete = request.form.getlist('delete')[0]

    ps = PatientService()
    res, data = ps.updateEventsByDoctorId(doctorId, eventId, session['User']['email'], delete)
    
    if res and data is not None:
        if delete == 'false':
            start = request.form.getlist('start')[0]
            end = request.form.getlist('end')[0]
            patientId = session['User']['id']
            ps.setAppointment(eventId, doctorId, patientId, start, end)
        else:
            ps.deleteAppointment(eventId)
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Updated!'}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# delete event
@patient_blueprint.route('/delete_events', methods=['POST'])
def deleteEvents():
    """
    delete events
    :return: json
    """
    eventId = request.form.getlist('event_id')[0]
    ps = PatientService()
    calendarId = session['User']['calendar_id']
    res, data = ps.deleteEventById(calendarId, eventId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Deleted!'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# delete event
@patient_blueprint.route('/get_appointments', methods=['GET'])
def getAppointments():
    """
    get all appointments
    :return: json
    """
    patientId = session['User']['id']
    ps = PatientService()
    res, data = ps.getAppointmentsById(patientId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': data['data']}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

web/templates/patient/account.html
{% extends "include/__layout.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css" rel='stylesheet' media='print'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/calendar.css')}}">
{% endblock %}

{% block mybody %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <h4 class="card-title">Account</h4>
            
            <form class="forms-sample" method="post" action="{{ url_for('patient.account') }}">
                {% from "include/__formhelper.html" import render_field %}
                {{ form.csrf_token }}
                <div class="form-group">
                <label for="username">Username</label>
                {{ render_field(form.username, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="email">Email address</label>
                {{ render_field(form.email, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="name">Name</label>
                {{ render_field(form.name, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleInputCity1">Sex</label>
                {{ render_field(form.sex, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleInputCity1">Age</label>
                {{ render_field(form.age, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleInputCity1">Birthday</label>
                {{ render_field(form.birthday, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleTextarea1">Phone No.</label>
                {{ render_field(form.phone, class="form-control", autofocus="true") }}
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
            </div>
        </div>
        </div>
        
    </div>
</div>
{% endblock %}

web/templates/patient/calendar.html
{% extends "include/__layout.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css" rel='stylesheet' media='print'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/calendar.css')}}">
{% endblock %}

{% block mybody %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                <button id="my_calendar" class="btn btn-primary btn-block">
                    <i class="mdi mdi-eye"></i> My Calendar</button>
                <!-- <div class="wrapper mt-4">
                    <div class="item-wrapper d-flex pb-4 border-bottom">
                    <div class="status-wrapper d-flex align-items-start pr-3">
                        <span class="bg-warning rounded-circle p-1 mt-2 mx-auto"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="d-block mb-1">Dentist appoinment:metro</h6>
                        <small class="d-block mb-2">
                        <strong>7 Feb 2017, 16:00</strong>
                        </small>
                        <small class="text-gray d-block">First Remainder : 1 Hours min before</small>
                    </div>
                    </div>
                    <div class="item-wrapper d-flex py-4">
                    <div class="status-wrapper d-flex align-items-start pr-3">
                        <span class="bg-success rounded-circle p-1 mt-2 mx-auto"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="d-block mb-1">Job appoinment:metro</h6>
                        <small class="d-block mb-2">
                        <strong>9 Feb 2017, 20:00</strong>
                        </small>
                        <small class="text-gray d-block">First Remainder : 1 Hours min before</small>
                    </div>
                    </div>
                </div> -->
                <div class="wrapper">
                    <div class="wrapper d-flex justify-content-between align-items-center mb-4">
                    <div class="d-flex align-items-center">
                        <small class="font-weight-bold mr-2 mb-0">Doctors</small>
                        <!-- <div class="badge badge-inverse-primary badge-pill">2</div> -->
                    </div>
                    <span class="text-gray">
                        <i class="mdi mdi-dots-horizontal"></i>
                    </span>
                    </div>
                    <div class="calendar-aside">
                    {% for doctor in doctors %}
                    <div class="list" id="{{doctor.id}}">
                        <img class="img-xs rounded-circle" src="{{url_for('static', filename='images/faces/face2.jpg')}}" alt="profile image">
                        <span class="user-text">{{doctor.username}}</span>
                        <span class="count online ml-auto">
                        <i class="close ml-auto mdi mdi-close-circle-outline"></i>
                        </span>
                    </div>
                    {% endfor %}
                    
                    </div>
                </div>
                </div>
                <div class="col-md-8">
                <div id="calendar"></div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Confirm Appointment</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <tbody>
                    <tr>
                        <th>Doctor</th>
                        <td id="doctor_name"></td>
                    </tr>
                    <tr>
                        <th>Patient</th>
                        <td>Jacob</td>
                    </tr>
                    <tr>
                        <th>Time</th>
                        <td><label class="badge badge-danger" id="appTime">12 May 2017</label></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <input type="hidden" name="doctor_id" value="">
            <input type="hidden" name="doctor_email" value="">
            <input type="hidden" name="patient_id" value="{{session.User.id}}">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="sub" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/hoverable-collapse.js')}}"></script>
    <script>
            (function($) {
                'use strict';
                $(function() {
                var style = getComputedStyle(document.body);
                var myEvents = []
                if ($('#calendar').length) {
                    $('#calendar').fullCalendar({
                    // defaultView: 'listWeek',
                    defaultView: 'agendaFourDay',
                    views: {
                        agendaFourDay: {
                            type: 'agenda',
                            duration: { days: 7 }
                        }
                    },
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'agendaFourDay,month,basicWeek,basicDay'
                    },
                    selectable: true,
                    eventClick: function(calEvent, jsEvent, view) {
                        // if ($(":input[name=doctor_id]").val()) {
                            if (calEvent.title == 'Free') {
                                // update patient's email into calendar event
                                var url = "{{url_for('patient.updateEventsByDoctorId')}}"
                                $.post(url, {
                                    "event_id": calEvent.id, 
                                    "doctor_id": $(":input[name=doctor_id]").val(), 
                                    "delete": "false",
                                    "start": calEvent.start.stripZone().format(),
                                    "end": calEvent.end.stripZone().format()
                                }, function(data){
                                    if(data.code == 1){
                                        calEvent.backgroundColor = '#EC4296'
                                        calEvent.title = 'Booked'
                                        $('#calendar').fullCalendar( 'updateEvent', calEvent )
                                    } 
                                })
                            } else {
                                // update patient's email into calendar event
                                var url = "{{url_for('patient.updateEventsByDoctorId')}}"
                                $.post(url, {
                                        "event_id": calEvent.id, 
                                        "doctor_id": '0', 
                                        "delete": "true"
                                    }, function(data){
                                    if(data.code == 1){
                                        // calEvent.backgroundColor = '#18d895'
                                        // calEvent.title = 'Free'
                                        $('#calendar').fullCalendar( 'removeEvents', calEvent.id )
                                    } 
                                })
                            }
                        // }
                    },
                    defaultDate: new Date(),
                    navLinks: true, // can click day/week names to navigate views
                    editable: true,
                    eventLimit: true, // allow "more" link when too many events
                    eventBackgroundColor: '#18d895',
                    eventTextColor: "white",
                    eventBorderColor: "transparent",
                    events: myEvents,
                    displayEventEnd: true
                    })
                }
                });
            })(jQuery);
            $(function(){
                $(".list").click(function(){
                    $(".list").css("backgroundColor", "#fff")
                    $('#calendar').fullCalendar('removeEvents')
                    var id = $(this).css("backgroundColor", "#eee").attr("id")
                    $(":input[name=doctor_id]").val(id)
                    var url = "/patient/get_events/"+id
                    $.getJSON(url, function(res){
                        if (res.code == 1) {
                            for(var i in res.data) {
                                var start = res.data[i]['start']['dateTime']
                                var end = res.data[i]['end']['dateTime']
                                var summary = res.data[i]['summary']
                                var eid = res.data[i]['id']
                                var bg = ''
                                if (summary == 'Free') {
                                    bg = '#18d895'
                                    $('#calendar').fullCalendar('renderEvent', {
                                        title: summary,
                                        start: start,
                                        end: end,
                                        id: eid,
                                        backgroundColor: bg,
                                        allDay: false
                                    });
                                }
                                if (summary == 'Booked') {
                                    bg = '#EC4296'
                                }
                                
                            }
                        }
                    })
                })
                let myCalendar = function(){
                    $.getJSON('{{url_for("patient.getAppointments")}}', function(res){
                        if (res.code == 1) {
                            for(var i in res.data) {
                                var start = res.data[i]['appointed_from']
                                var end = res.data[i]['appointed_to']
                                var summary = 'Booked'
                                var eid = res.data[i]['google_event_id']
                                var bg = '#EC4296'
                                $('#calendar').fullCalendar('renderEvent', {
                                    title: summary,
                                    start: start,
                                    end: end,
                                    id: eid,
                                    backgroundColor: bg,
                                    allDay: false
                                });
                            }
                        }
                    })
                }
                myCalendar()
                $("#my_calendar").click(function(){
                    $('#calendar').fullCalendar( 'removeEvents' )
                    $(":input[name=doctor_id]").val("")
                    myCalendar()
                })
            })
        </script>
{% endblock %}

web/templates/patient/register.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Patient Register</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{{url_for('static', filename='iconfonts/mdi/css/materialdesignicons.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/vendor.bundle.base.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/vendor.bundle.addons.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <h2 class="text-center mb-4">Patient Register</h2>
            <div class="auto-form-wrapper">
              <form method="post" action="{{url_for('patient.register')}}">
                {% from "include/__formhelper.html" import render_register_field %}
                {{ form.csrf_token }}
                {{ render_register_field(form.username, class="form-control", placeholder="Username", autofocus="true") }}
                {{ render_register_field(form.email, class="form-control", placeholder="Email") }}
                {{ render_register_field(form.password, class="form-control", placeholder="Password") }}  
                {{ render_register_field(form.confirm, class="form-control", placeholder="Confirm Password") }}
                <div class="form-group">
                  <button class="btn btn-primary submit-btn btn-block">Register</button>
                </div>
                <div class="text-block text-center my-3">
                  <span class="text-small font-weight-semibold">Already have and account ?</span>
                  <a href="{{ url_for('login') }}" class="text-black text-small">Login</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <script src="{{url_for('static', filename='js/vendor.bundle.base.js')}}"></script>
  <script src="{{url_for('static', filename='js/vendor.bundle.addons.js')}}"></script>
  <script src="{{url_for('static', filename='js/off-canvas.js')}}"></script>
  <script src="{{url_for('static', filename='js/misc.js')}}"></script>
</body>

</html>