web/app/doctor/forms.py
# import necessary packages
from wtforms import Form, StringField, PasswordField, validators, SelectField, TextAreaField
from flask import session
from wtforms.validators import ValidationError
from wtforms.validators import ValidationError
from app.patient.patient_services import PatientService
from app.clerk.clerk_services import ClerkService
from app.doctor.doctor_services import DoctorService
from init import session

# define the notes form model
class NoteForm(Form):
    """
    edit notes form
    """
    description = TextAreaField('Description', validators=[
        validators.DataRequired(),
    ])

# define the diagnoses form model
class DiagnoseForm(Form):
    """
    edit diagnoses form
    """
    description = TextAreaField('Description', validators=[
        validators.DataRequired(),
    ])

web/app/patient/forms.py
# import necessary packages
from wtforms import Form, StringField, PasswordField, validators, SelectField
from flask import session
from wtforms.validators import ValidationError
from wtforms.validators import ValidationError
from app.patient.patient_services import PatientService
from app.clerk.clerk_services import ClerkService
from app.doctor.doctor_services import DoctorService
from init import session

# define the reg form model
class RegForm(Form):
    """
    patient register form
    """
    username = StringField('username', validators=[
        validators.DataRequired(),
        validators.Length(min=4, max=25)
    ])

    email = StringField('email', validators=[
        validators.DataRequired(),
        validators.Email()
    ])

    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])

    confirm = PasswordField('Repeat Password')

# define the login form model
class LoginForm(Form):
    """
    patient sign in form
    """
    username = StringField('username', validators=[
        validators.DataRequired()
    ])

    password = PasswordField('password', validators=[
        validators.DataRequired()
    ])

    role = SelectField('role', choices=[('1', 'Patient'), ('2', 'Doctor'), ('3', 'Clerk')], validators=[
        validators.DataRequired()
    ])

    # validate username and password
    def validate_username(form, field):
        username = field.data
        password = form.password.data
        role = form.role.data
        if role == '1':
            ps = PatientService()
            payload = {
                'patient': {
                    'username': username,
                    'password': password
                }
            }
            res, data = ps.login(payload)
            
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Patient'
                session['User'] = d
        elif role == '2':
            ds = DoctorService()
            payload = {
                'doctor': {
                    'username': username,
                    'password': password
                }
            }
            res, data = ds.login(payload)
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Doctor'
                session['User'] = d
        elif role == '3':
            cs = ClerkService()
            payload = {
                'clerk': {
                    'username': username,
                    'password': password
                }
            }
            res, data = cs.login(payload)
            if res is False:
                raise ValidationError('Username Or Password Is Invalid')
            else:
                d = data['data']
                d['type'] = 'Clerk'
                session['User'] = d

# define form for account
class UpdateForm(Form):
    """
    patient update account form
    """
    username = StringField('Username', validators=[
        validators.DataRequired()
    ])

    sex = SelectField('Sex', choices=[('1', 'Male'), ('2', 'Female')], validators=[
        validators.DataRequired()
    ])

    name = StringField('Name', validators=[
        validators.DataRequired()
    ])

    birthday = StringField('Birthday', validators=[
        validators.DataRequired()
    ])

    phone = StringField('Phone No', validators=[
        validators.DataRequired()
    ])

    email = StringField('Email', validators=[
        validators.DataRequired()
    ])

    age = StringField('Age', validators=[
        validators.DataRequired()
    ])

web/app/doctor/views.py
# import necessary packages
from flask import Blueprint, Flask, render_template, session, redirect, url_for, request, jsonify, make_response
from app.doctor.doctor_services import DoctorService
from app.doctor.forms import NoteForm, DiagnoseForm
import json

# create blueprint object
doctor_blueprint = Blueprint(
    'doctor', 
    __name__,
    template_folder='../../templates',
    url_prefix='/doctor'
)

# setting
def doctorSetting():
    """
    menu setting
    :return: menu object
    """
    settings = {
        'title' : 'Doctor',
        'menu' : {
            'All scheduled patients': {
                'new' : True,
                'icon' : 'mdi mdi-account',
                'url' : url_for('doctor.patients'),
            },
            'Set Weekly Availability' : {
                'icon' : 'mdi mdi-calendar',
                'url' : url_for('doctor.setCalendar'),
            }
        }
    }
    return settings

@doctor_blueprint.route('/index')
def index():
    """
    index
    :return: default page
    """
    return redirect(url_for('doctor.setCalendar'))

@doctor_blueprint.route('/all_patients')
def patients():
    """
    get all patients
    :return: render page
    """
    ds = DoctorService()
    doctorId = session['User']['id']
    res, data = ds.getAllPatients(doctorId)    
    return render_template('doctor/patients.html', **doctorSetting(), patients=data['data'])

@doctor_blueprint.route('/edit_notes/<appointment_id>', methods=['GET', 'POST'])
def editNotes(appointment_id):
    """
    edit notes
    :param appointment_id: app id
    :return: render page
    """
    ds = DoctorService()
    form = NoteForm(request.form)
    res, data = ds.getAppointmentById(appointment_id)
    if request.method == 'POST' and form.validate():
        res = ds.editNotes(appointment_id, form.description.data)
    else:
        form.description.data = data['data']['notes']
    return render_template('doctor/edit_notes.html', **doctorSetting(), form=form, address='/doctor/edit_notes/{}'.format(appointment_id))

@doctor_blueprint.route('/edit_diagnoses/<appointment_id>', methods=['GET', 'POST'])
def editDiagnoses(appointment_id):
    """
    edit diagnoses
    :param appointment_id: app id
    :return: render page
    """
    ds = DoctorService()
    form = DiagnoseForm(request.form)
    res, data = ds.getAppointmentById(appointment_id)
    if request.method == 'POST' and form.validate():
        res = ds.editDiags(appointment_id, form.description.data)
    else:
        form.description.data = data['data']['diagnoses']
    return render_template('doctor/edit_diagnoses.html', **doctorSetting(), form=form, address='/doctor/edit_diagnoses/{}'.format(appointment_id))

@doctor_blueprint.route('/history/<patient_id>')
def history(patient_id):
    """
    get all history by patient id
    :param patient_id: patient id
    :return: render page
    """
    ds = DoctorService()
    his, data = ds.getAppointmentsByPatientId(patient_id)
    return render_template('doctor/history.html', **doctorSetting(), history=data['data'])

@doctor_blueprint.route('/set_calendar')
def setCalendar():
    """
    set calendar
    :return: render page
    """
    return render_template('doctor/set_calendar.html', **doctorSetting())

# set free time
@doctor_blueprint.route('/set_free_time', methods=['POST'])
def setFreeTime():
    """
    set free time
    :return: json
    """
    start = request.form.getlist('start')[0]
    end = request.form.getlist('end')[0]
    ds = DoctorService()
    payload = {
        'doctor_email': session['User']['email'],
        'doctor_id': session['User']['id'],
        'start': start,
        'end': end
    }
    res, data = ds.setFreeTime(payload)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Set!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# get free time
@doctor_blueprint.route('/get_free_time', methods=['GET'])
def getFreeTime():
    """
    get free time
    :return: json
    """
    ds = DoctorService()
    calendarId = session['User']['calendar_id']
    if calendarId is None:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': []}), 201)
    
    res, data = ds.getFreeTime(calendarId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# delete free time
@doctor_blueprint.route('/delete_free_time', methods=['POST'])
def deleteFreeTime():
    """
    delete free time
    :return: json
    """
    calendarId = session['User']['calendar_id']
    freeId = request.form.getlist('freeid')[0]
    ds = DoctorService()
    res, data = ds.deleteFreeTime(calendarId, freeId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Deleted!'}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

web/app/patient/views.py
# append path
import sys
import os
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

# import necessary packages
from flask import Blueprint, Flask, render_template, session, redirect, url_for, request, jsonify, make_response
from forms import RegForm, UpdateForm
from app.patient.patient_services import PatientService
from app.doctor.doctor_services import DoctorService
import time
from init import app

# create blueprint object
patient_blueprint = Blueprint(
    'patient', 
    __name__,
    template_folder='../../templates',
    url_prefix='/patient'
)

# setting
def patientSetting():

    """
    menu setting
    :return:  object
    """
    settings = {
        'title' : 'Patient',
        'menu' : {
            'Appointment' : {
                'icon' : 'mdi mdi-calendar-clock',
                'new' : True,
                'url' : url_for('patient.makeAppointment'),
            },
            'Account' : {
                'icon' : 'mdi mdi-account',
                'url' : url_for('patient.account'),
            }
        }
    }
    return settings

@patient_blueprint.route('/index')
def index():
    """
    index
    :return: default page
    """
    return redirect(url_for('patient.account'))

@patient_blueprint.route('/account', methods=['GET', 'POST'])
def account():
    """
    show account page
    :return: render page
    """
    form = UpdateForm(request.form)
    if request.method == 'GET':
        form.username.data = session['User']['username']
        form.name.data = session['User']['name']
        form.email.data = session['User']['email']
        form.age.data = session['User']['age']
        form.sex.data = session['User']['sex']
        form.birthday.data = session['User']['birthday']
        form.phone.data = session['User']['phone']
    if request.method == 'POST' and form.validate():
        # update data of patient
        ps = PatientService()
        payload = {
            'patient': form.data
        }
        res, data = ps.update(payload)
        if res:
            return render_template('patient/account.html', **patientSetting(), form = form)
    return render_template('patient/account.html', **patientSetting(), form = form)

# make appointment
@patient_blueprint.route('/make_appointment')
def makeAppointment():
    """
    make an appointment
    :return: render page
    """
    ds = DoctorService()
    res, doctors = ds.getAll()
    data = doctors['data']
    return render_template('patient/calendar.html', **patientSetting(), doctors=data)

# get doctor
@patient_blueprint.route('/get_doctor/<doctor_id>')
def getDoctor(doctor_id):
    """
    get one doctor
    :param doctor_id: doctor id
    :return: json
    """
    ds = DoctorService()
    res, data = ds.getDoctorById(doctor_id)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Fetched!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# @patient_blueprint.route('/delete_appointment')
# def deleteAppointment():
#     return render_template('patient/calendar.html', **patientSetting())

# register a patient
@patient_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    register a patient
    :return:render page
    """
    form = RegForm(request.form)
    if request.method == 'POST' and form.validate():
        # pass the validation, request API
        ps = PatientService()
        payload = {
            'patient' : {
                'username': form.username.data,
                'password': form.password.data,
                'email': form.email.data,
                'created_at': time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            }
        }
        res, data = ps.register(payload)
        if res:
            return redirect(url_for('login'))
    return render_template('patient/register.html', form=form)

# get events by doctorid
@patient_blueprint.route('/get_events/<doctor_id>', methods=['GET'])
def getEventsByDoctorId(doctor_id):
    """
    get all events by doctor id
    :param doctor_id: doctor id
    :return: json
    """
    ps = PatientService()
    res, data = ps.getEventsByDoctorId(doctor_id)
    if res and data is not None:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Fetched!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# get events by doctorid
@patient_blueprint.route('/update_events', methods=['POST'])
def updateEventsByDoctorId():
    """
    update events by doctor id
    :return: json
    """
    doctorId = request.form.getlist('doctor_id')[0]
    eventId = request.form.getlist('event_id')[0]
    delete = request.form.getlist('delete')[0]

    ps = PatientService()
    res, data = ps.updateEventsByDoctorId(doctorId, eventId, session['User']['email'], delete)
    
    if res and data is not None:
        if delete == 'false':
            start = request.form.getlist('start')[0]
            end = request.form.getlist('end')[0]
            patientId = session['User']['id']
            ps.setAppointment(eventId, doctorId, patientId, start, end)
        else:
            ps.deleteAppointment(eventId)
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Updated!'}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# delete event
@patient_blueprint.route('/delete_events', methods=['POST'])
def deleteEvents():
    """
    delete events
    :return: json
    """
    eventId = request.form.getlist('event_id')[0]
    ps = PatientService()
    calendarId = session['User']['calendar_id']
    res, data = ps.deleteEventById(calendarId, eventId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Deleted!'}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

# delete event
@patient_blueprint.route('/get_appointments', methods=['GET'])
def getAppointments():
    """
    get all appointments
    :return: json
    """
    patientId = session['User']['id']
    ps = PatientService()
    res, data = ps.getAppointmentsById(patientId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': data['data']}), 201)
    return make_response(jsonify({'code': -1, 'msg': data}), 201)

web/templates/doctor/edit_diagnoses.html
{% extends "include/__layout.html" %}

{% block mybody %}
<div class="card">
    <div class="card-body">
    <h4 class="card-title">Add Diagnoses</h4>
    <form class="forms-sample" action="{{address}}" method="post">
        {% from "include/__formhelper.html" import render_field %}
        {{ form.csrf_token }}
        {{ render_field(form.description, class="form-control", placeholder="Diagnoses", rows="10") }}
        <br>
      <button type="submit" class="btn btn-success mr-2">Submit</button>
      <button class="btn btn-light">Cancel</button>
    </form>
  </div>
</div>
{% endblock %}

web/templates/doctor/edit_notes.html
{% extends "include/__layout.html" %}

{% block mybody %}
<div class="card">
    <div class="card-body">
    <h4 class="card-title">Add Notes</h4>
    <form class="forms-sample" action="{{address}}" method="post">
        {% from "include/__formhelper.html" import render_field %}
        {{ form.csrf_token }}
        {{ render_field(form.description, class="form-control", placeholder="Notes", rows="10") }}
        <br>
      <button type="submit" class="btn btn-success mr-2">Submit</button>
      <button class="btn btn-light">Cancel</button>
    </form>
  </div>
</div>
{% endblock %}

web/templates/doctor/history.html
{% extends "include/__layout.html" %}

{% block mybody %}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Doctor</th>
                <th>Appointment Start</th>
                <th>Appointment End</th>
                <th>Notes And Diagnoses</th>
              </tr>
            </thead>
            <tbody>
                {% for item in history %}
              <tr>
                <td><img src="{{url_for('static', filename='images/faces-clipart/pic-1.png')}}" alt="image" />&nbsp;&nbsp;&nbsp;{{item['doctor']['name']}}</td>
                <td>{{item['appointed_from']}}</td>
                <td>{{item['appointed_to']}}</td>
                <td class="text-info"> 
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#note-{{item['id']}}">
                        <i class="mdi mdi-upload"></i>View Note
                    </button>
                    <button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#diagnose-{{item['id']}}">
                        <i class="mdi mdi-upload"></i>View Diagnose
                    </button>
                </td>
                <!-- Note Modal -->
                <div class="modal fade" id="note-{{item['id']}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Note</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            {{item['notes']}}
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    </div>
                </div>

                <!-- Diagnose Modal -->
                <div class="modal fade" id="diagnose-{{item['id']}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Diagnose</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            {{item['diagnoses']}}
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    </div>
                </div>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web/templates/doctor/patients.html
{% extends "include/__layout.html" %}

{% block mybody %}
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">All Scheduled Patients</h4>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th></th>
                <th>
                  Username
                </th>
                <th>
                  Full name
                </th>
                <th>
                  Email
                </th>
                <th>
                    Age
                </th>
                <th>
                    Sex
                </th>
                <th>
                    Phone
                </th>
                
                <th>
                  Appointment Date
                </th>
                <th>
                  Operate
                </th>
              </tr>
            </thead>
            <tbody>
                {% for patient in patients %}
              <tr>
                <td class="py-1">
                  <img src="{{url_for('static', filename='images/faces-clipart/pic-1.png')}}" alt="image" />
                </td>
                <td>
                    {{patient['patient']['username']}}
                </td>
                <td>
                    {{patient['patient']['name']}}
                </td>
                <td>
                    {{patient['patient']['email']}}
                </td>
                <td>
                    {{patient['patient']['age']}}
                </td>
                <td>
                    {% if patient['patient']['sex'] == 1%}
                        Male
                    {% else %}
                        Female
                    {% endif %}
                </td>
                <td>
                    {{patient['patient']['phone']}}
                </td>
                <td style="width: 100px">
                    {{patient['appointed_from']}} ~<br> {{patient['appointed_to']}}
                </td>
                <td>
                    <button type="button" class="btn btn-outline-info btn-xs" onclick="location.href='/doctor/edit_notes/{{patient['id']}}'">
                        <i class="mdi mdi-file-document"></i>Add Notes
                    </button>
                    <button type="button" class="btn btn-outline-primary btn-xs" onclick="location.href='/doctor/edit_diagnoses/{{patient['id']}}'">
                        <i class="mdi mdi-file-document"></i>Add Diagnoses
                    </button>
                    <button type="button" class="btn btn-outline-warning btn-xs" onclick="location.href='/doctor/history/{{patient['patient_id']}}'">
                        <i class="mdi mdi-cloud-download"></i>History
                    </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web/templates/doctor/set_calendar.html
{% extends "include/__layout.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css" rel='stylesheet' media='print'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/calendar.css')}}">
{% endblock %}

{% block mybody %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div id="calendar"></div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/hoverable-collapse.js')}}"></script>
    <script>
        (function($) {
            'use strict';
            $(function() {
            let ev, bg
            $.getJSON('{{url_for("doctor.getFreeTime")}}', function(res){
                for(var i in res.data) {
                    if (res.data[i]['summary'] == 'Free') {
                        bg = '#18d895'
                    } else {
                        bg = '#EC4296'
                    }
                    $('#calendar').fullCalendar('renderEvent', {
                        title: res.data[i]['summary'],
                        start: res.data[i]['start']['dateTime'],
                        end: res.data[i]['end']['dateTime'],
                        id: res.data[i]['id'],
                        backgroundColor: bg,
                        allDay: false
                    });
                }
                ev = $('#calendar').fullCalendar('clientEvents')
            })
            var style = getComputedStyle(document.body);
            if ($('#calendar').length) {
                $('#calendar').fullCalendar({
                defaultView: 'agendaFourDay',
                views: {
                    agendaFourDay: {
                        type: 'agenda',
                        duration: { days: 7 }
                    }
                },
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'listWeek,agendaFourDay,month,basicWeek,basicDay'
                },
                selectable: true,
                select: function(startDate, endDate) {
                    let url = "{{url_for('doctor.setFreeTime')}}"
                    $.post(url, {"start": startDate.stripZone().format(), "end": endDate.stripZone().format()}, function(res){
                        $('#calendar').fullCalendar('renderEvent', {
                            title: 'Free',
                            start: startDate.stripZone().format(),
                            end: endDate.stripZone().format(),
                            id: res.data['id'],
                            allDay: false
                        });
                        ev = $('#calendar').fullCalendar('clientEvents')
                    })
                },
                eventClick: function(calEvent, jsEvent, view) {
                    // id = calEvent.id
                    let url = "{{url_for('doctor.deleteFreeTime')}}" 
                    $.post(url, {"freeid": calEvent.id}, function(data){
                        $('#calendar').fullCalendar( 'removeEvents', [calEvent.id] )
                    })
                },
                defaultDate: new Date(),
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                eventBackgroundColor: '#18d895',
                eventTextColor: "white",
                eventBorderColor: "transparent",
                events: ev
                })
            }
            });
        })(jQuery);
    </script>
{% endblock %}