web/app/clerk/forms.py
# import necessary packages
from wtforms import Form, StringField, PasswordField, validators, SelectField
from flask import session
from wtforms.validators import ValidationError
from wtforms.validators import ValidationError
from app.patient.patient_services import PatientService
from app.clerk.clerk_services import ClerkService
from init import session

# define the reg form model
class AddDoctorForm(Form):
    """
    Add doctor form
    """
    username = StringField('Username', validators=[
        validators.DataRequired()
    ])

    sex = SelectField('Sex', choices=[('1', 'Male'), ('2', 'Female')], validators=[
        validators.DataRequired()
    ])

    name = StringField('Name', validators=[
        validators.DataRequired()
    ])

    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])

    confirm = PasswordField('Repeat Password')

    phone = StringField('Phone No', validators=[
        validators.DataRequired()
    ])

    email = StringField('Email', validators=[
        validators.DataRequired()
    ])

    age = StringField('Age', validators=[
        validators.DataRequired()
    ])

web/app/doctor/forms.py
# import necessary packages
from wtforms import Form, StringField, PasswordField, validators, SelectField, TextAreaField
from flask import session
from wtforms.validators import ValidationError
from wtforms.validators import ValidationError
from app.patient.patient_services import PatientService
from app.clerk.clerk_services import ClerkService
from app.doctor.doctor_services import DoctorService
from init import session

# define the notes form model
class NoteForm(Form):
    """
    edit notes form
    """
    description = TextAreaField('Description', validators=[
        validators.DataRequired(),
    ])

# define the diagnoses form model
class DiagnoseForm(Form):
    """
    edit diagnoses form
    """
    description = TextAreaField('Description', validators=[
        validators.DataRequired(),
    ])

web/app/clerk/views.py
# import necessary packages
from flask import Blueprint, Flask, render_template, session, redirect, url_for, request, jsonify, make_response
from app.clerk.forms import AddDoctorForm
from app.doctor.doctor_services import DoctorService
from app.clerk.clerk_services import ClerkService
import time, json

# create blueprint object
clerk_blueprint = Blueprint(
    'clerk', 
    __name__,
    template_folder='../../templates',
    url_prefix='/clerk'
)

# setting
def clerkSetting():
    """
    define menu
    :return: menu object
    """
    settings = {
        'title' : 'Clerk',
        'menu' : {
            'Doctor Appointments' : {
                'icon' : 'mdi mdi-calendar-clock',
                'url': url_for('clerk.doctorsCalendar'),
            },
            'Add Doctor': {
                'icon' : 'mdi mdi-account',
                'url': url_for('clerk.addDoctor'),
            },
            'All Doctors': {
                'icon' : 'mdi mdi-account',
                'url': url_for('clerk.doctorsList'),
            },
            'Statistics': {
                'icon' : 'mdi mdi-chart-bar',
                'url': url_for('clerk.statistics'),
            }
        }
    }
    return settings

@clerk_blueprint.route('/index')
def index():
    """
    index
    :return: default page
    """
    return redirect(url_for('clerk.addDoctor'))

@clerk_blueprint.route('/add_doctor', methods=['GET', 'POST'])
def addDoctor():
    """
    add a doctor
    :return: render page or redirect
    """
    form = AddDoctorForm(request.form)
    if request.method == 'POST' and form.validate():
        # pass the validation, request API
        ds = DoctorService()
        dd = form.data
        dd['created_at'] = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        payload = {
            'doctor' : dd
        }
        res, data = ds.register(payload)
        
        if res:
            return redirect(url_for('clerk.doctorsList'))
    return render_template('clerk/add_doctor.html', **clerkSetting(), form=form)

@clerk_blueprint.route('/doctors')
def doctorsList():
    """
    get doctor list
    :return:render page
    """
    ds = DoctorService()
    res, doctors = ds.getAll()
    data = doctors['data']
    return render_template('clerk/doctors.html', **clerkSetting(), doctors=data)

@clerk_blueprint.route('/doctors_calendar')
def doctorsCalendar():
    """
    get doctor calendar
    :return: render page
    """
    ds = DoctorService()
    res, doctors = ds.getAll()
    data = doctors['data']
    return render_template('clerk/doctors_calendar.html', **clerkSetting(), doctors=data)

# set free time
@clerk_blueprint.route('/set_free_time/<doctor_id>', methods=['POST'])
def setFreeTime(doctor_id):
    """
    set free time for doctor
    :param doctor_id: doctor id
    :return: json
    """
    start = request.form.getlist('start')[0]
    end = request.form.getlist('end')[0]
    ds = DoctorService()
    res, data = ds.getDoctorById(doctor_id)
    payload = {
        'doctor_email': data['data']['email'],
        'doctor_id': doctor_id,
        'start': start,
        'end': end
    }
    res, data = ds.setFreeTime(payload)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Set!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# get free time
@clerk_blueprint.route('/get_free_time/<doctor_id>', methods=['GET'])
def getFreeTime(doctor_id):
    """
    get free time
    :param doctor_id: doctor id
    :return: json
    """
    ds = DoctorService()
    res, data = ds.getDoctorById(doctor_id)
    calendarId = data['data']['calendar_id']
    if calendarId is None:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': []}), 201)
    
    res, data = ds.getFreeTime(calendarId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# delete free time
@clerk_blueprint.route('/delete_free_time/<doctor_id>', methods=['POST'])
def deleteFreeTime(doctor_id):
    """
    delete free time
    :param doctor_id: doctor id
    :return: json
    """
    ds = DoctorService()
    res, data = ds.getDoctorById(doctor_id)
    calendarId = data['data']['calendar_id']
    freeId = request.form.getlist('freeid')[0]
    
    res, data = ds.deleteFreeTime(calendarId, freeId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Deleted!'}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# statistics
@clerk_blueprint.route('/statistics', methods=['GET'])
def statistics():
    """
    get statistics
    :return: render page
    """
    return render_template('clerk/statistics.html', **clerkSetting())

# get Json
@clerk_blueprint.route('/statistics/json', methods=['GET'])
def staJson():
    """
    get statistics data
    :return: json
    """
    cs = ClerkService()
    res, data = cs.getStatistics()
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Fetched!', "data": data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

web/app/doctor/views.py
# import necessary packages
from flask import Blueprint, Flask, render_template, session, redirect, url_for, request, jsonify, make_response
from app.doctor.doctor_services import DoctorService
from app.doctor.forms import NoteForm, DiagnoseForm
import json

# create blueprint object
doctor_blueprint = Blueprint(
    'doctor', 
    __name__,
    template_folder='../../templates',
    url_prefix='/doctor'
)

# setting
def doctorSetting():
    """
    menu setting
    :return: menu object
    """
    settings = {
        'title' : 'Doctor',
        'menu' : {
            'All scheduled patients': {
                'new' : True,
                'icon' : 'mdi mdi-account',
                'url' : url_for('doctor.patients'),
            },
            'Set Weekly Availability' : {
                'icon' : 'mdi mdi-calendar',
                'url' : url_for('doctor.setCalendar'),
            }
        }
    }
    return settings

@doctor_blueprint.route('/index')
def index():
    """
    index
    :return: default page
    """
    return redirect(url_for('doctor.setCalendar'))

@doctor_blueprint.route('/all_patients')
def patients():
    """
    get all patients
    :return: render page
    """
    ds = DoctorService()
    doctorId = session['User']['id']
    res, data = ds.getAllPatients(doctorId)    
    return render_template('doctor/patients.html', **doctorSetting(), patients=data['data'])

@doctor_blueprint.route('/edit_notes/<appointment_id>', methods=['GET', 'POST'])
def editNotes(appointment_id):
    """
    edit notes
    :param appointment_id: app id
    :return: render page
    """
    ds = DoctorService()
    form = NoteForm(request.form)
    res, data = ds.getAppointmentById(appointment_id)
    if request.method == 'POST' and form.validate():
        res = ds.editNotes(appointment_id, form.description.data)
    else:
        form.description.data = data['data']['notes']
    return render_template('doctor/edit_notes.html', **doctorSetting(), form=form, address='/doctor/edit_notes/{}'.format(appointment_id))

@doctor_blueprint.route('/edit_diagnoses/<appointment_id>', methods=['GET', 'POST'])
def editDiagnoses(appointment_id):
    """
    edit diagnoses
    :param appointment_id: app id
    :return: render page
    """
    ds = DoctorService()
    form = DiagnoseForm(request.form)
    res, data = ds.getAppointmentById(appointment_id)
    if request.method == 'POST' and form.validate():
        res = ds.editDiags(appointment_id, form.description.data)
    else:
        form.description.data = data['data']['diagnoses']
    return render_template('doctor/edit_diagnoses.html', **doctorSetting(), form=form, address='/doctor/edit_diagnoses/{}'.format(appointment_id))

@doctor_blueprint.route('/history/<patient_id>')
def history(patient_id):
    """
    get all history by patient id
    :param patient_id: patient id
    :return: render page
    """
    ds = DoctorService()
    his, data = ds.getAppointmentsByPatientId(patient_id)
    return render_template('doctor/history.html', **doctorSetting(), history=data['data'])

@doctor_blueprint.route('/set_calendar')
def setCalendar():
    """
    set calendar
    :return: render page
    """
    return render_template('doctor/set_calendar.html', **doctorSetting())

# set free time
@doctor_blueprint.route('/set_free_time', methods=['POST'])
def setFreeTime():
    """
    set free time
    :return: json
    """
    start = request.form.getlist('start')[0]
    end = request.form.getlist('end')[0]
    ds = DoctorService()
    payload = {
        'doctor_email': session['User']['email'],
        'doctor_id': session['User']['id'],
        'start': start,
        'end': end
    }
    res, data = ds.setFreeTime(payload)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Set!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# get free time
@doctor_blueprint.route('/get_free_time', methods=['GET'])
def getFreeTime():
    """
    get free time
    :return: json
    """
    ds = DoctorService()
    calendarId = session['User']['calendar_id']
    if calendarId is None:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': []}), 201)
    
    res, data = ds.getFreeTime(calendarId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Get!', 'data': data['data']}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

# delete free time
@doctor_blueprint.route('/delete_free_time', methods=['POST'])
def deleteFreeTime():
    """
    delete free time
    :return: json
    """
    calendarId = session['User']['calendar_id']
    freeId = request.form.getlist('freeid')[0]
    ds = DoctorService()
    res, data = ds.deleteFreeTime(calendarId, freeId)
    if res:
        return make_response(jsonify({'code': 1, 'msg': 'Successfully Deleted!'}), 201)
    else:
        return make_response(jsonify({'code': -1, 'msg': 'Failed'}), 400)

web/templates/clerk/add_doctor.html
{% extends "include/__layout.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css" rel='stylesheet' media='print'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/calendar.css')}}">
{% endblock %}

{% block mybody %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <h4 class="card-title">Add A Doctor</h4>
            
            <form class="forms-sample" method="post" action="{{ url_for('clerk.addDoctor') }}">
                {% from "include/__formhelper.html" import render_field %}
                {{ form.csrf_token }}
                <div class="form-group">
                <label for="username">Username</label>
                {{ render_field(form.username, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="email">Email address</label>
                {{ render_field(form.email, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="email">Password</label>
                {{ render_field(form.password, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="email">Confirm Password</label>
                {{ render_field(form.confirm, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="name">Name</label>
                {{ render_field(form.name, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleInputCity1">Sex</label>
                {{ render_field(form.sex, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleInputCity1">Age</label>
                {{ render_field(form.age, class="form-control", autofocus="true") }}
                </div>
                <div class="form-group">
                <label for="exampleTextarea1">Phone No.</label>
                {{ render_field(form.phone, class="form-control", autofocus="true") }}
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
            </div>
        </div>
        </div>
        
    </div>
</div>
{% endblock %}

web/templates/clerk/doctors.html
{% extends "include/__layout.html" %}

{% block mybody %}
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">All Doctors</h4>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                  <th></th>
                <th>
                  User Name
                </th>
                <th>
                  Full name
                </th>
                <th>
                  Email
                </th>
                <th>
                  Phone No.
                </th>
                <th>Sex</th>
                <th>Age</th>
                
              </tr>
            </thead>
            <tbody>
            {% for doctor in doctors %}
              <tr>
                <td class="py-1">
                  <img src="{{url_for('static', filename='images/faces-clipart/pic-1.png')}}" alt="image" />
                </td>
                <td>
                    {{doctor.username}}
                </td>
                <td>
                    {{doctor.name}}
                </td>
                <td>
                    {{doctor.email}}
                </td>
                <td>
                    {{doctor.phone}}
                </td>
                <td>
                    {% if doctor.sex == 1 %}
                        Male
                    {% else %}
                        Female
                    {% endif %}
                </td>
                <td>
                    {{doctor.age}}
                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web/templates/clerk/doctors_calendar.html
{% extends "include/__layout.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css" rel='stylesheet' media='print'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/calendar.css')}}">
{% endblock %}

{% block mybody %}
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                
                <div class="wrapper">
                    <div class="wrapper d-flex justify-content-between align-items-center mb-4">
                    <div class="d-flex align-items-center">
                        <small class="font-weight-bold mr-2 mb-0">Doctors</small>
                        <!-- <div class="badge badge-inverse-primary badge-pill">2</div> -->
                    </div>
                    <span class="text-gray">
                        <i class="mdi mdi-dots-horizontal"></i>
                    </span>
                    </div>
                    <div class="calendar-aside">
                    {% for doctor in doctors %}
                    <div class="list" id="{{doctor.id}}">
                        <img class="img-xs rounded-circle" src="{{url_for('static', filename='images/faces/face2.jpg')}}" alt="profile image">
                        <span class="user-text">{{doctor.username}}</span>
                        <span class="count online ml-auto">
                        <i class="close ml-auto mdi mdi-close-circle-outline"></i>
                        </span>
                    </div>
                    {% endfor %}
                    
                    </div>
                </div>
                </div>
                <div class="col-md-8">
                <div id="calendar"></div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Confirm Appointment</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <tbody>
                    <tr>
                        <th>Doctor</th>
                        <td id="doctor_name"></td>
                    </tr>
                    <tr>
                        <th>Patient</th>
                        <td>Jacob</td>
                    </tr>
                    <tr>
                        <th>Time</th>
                        <td><label class="badge badge-danger" id="appTime">12 May 2017</label></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <input type="hidden" name="doctor_id" value="">
            <input type="hidden" name="doctor_email" value="">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="sub" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/hoverable-collapse.js')}}"></script>
    <script>
        (function($) {
            'use strict';
            $(function() {
            let ev, bg
            var style = getComputedStyle(document.body);
            if ($('#calendar').length) {
                $('#calendar').fullCalendar({
                // defaultView: 'listWeek',
                defaultView: 'agendaFourDay',
                views: {
                    agendaFourDay: {
                        type: 'agenda',
                        duration: { days: 7 }
                    }
                },
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'agendaFourDay,month,basicWeek,basicDay'
                },
                selectable: true,
                select: function(startDate, endDate) {
                    let id = $(":input[name=doctor_id]").val()
                    let url = "/clerk/set_free_time/" + id
                    $.post(url, {"start": startDate.format(), "end": endDate.format()}, function(res){
                        $('#calendar').fullCalendar('renderEvent', {
                            title: 'Free',
                            start: startDate.format(),
                            end: endDate.format(),
                            id: res.data['id'],
                            allDay: false
                        });
                    })
                },
                eventClick: function(calEvent, jsEvent, view) {
                    // id = calEvent.id
                    let id = $(":input[name=doctor_id]").val()
                    let url = "/clerk/delete_free_time/" + id 
                    $.post(url, {"freeid": calEvent.id}, function(data){
                        $('#calendar').fullCalendar( 'removeEvents', [calEvent.id] )
                    })
                },
                defaultDate: new Date(),
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                eventBackgroundColor: '#18d895',
                eventTextColor: "white",
                eventBorderColor: "transparent",
                events: []
                })
            }
            });
        })(jQuery);
        $(function(){
            let id = $(".list").first().css("backgroundColor", "#eee").attr("id")
            if (id) {
                $(":input[name=doctor_id]").val(id)
                var url = "/clerk/get_free_time/"+id
                $.getJSON(url, function(res){
                    if (res.code == 1) {
                        for(var i in res.data) {
                            var start = res.data[i]['start']['dateTime']
                            var end = res.data[i]['end']['dateTime']
                            var summary = res.data[i]['summary']
                            var eid = res.data[i]['id']
                            var bg = ''
                            if (summary == 'Free') {
                                bg = '#18d895'
                            }
                            if (summary == 'Booked') {
                                bg = '#EC4296'
                            }
                            $('#calendar').fullCalendar('renderEvent', {
                                title: summary,
                                start: start,
                                end: end,
                                id: eid,
                                backgroundColor: bg,
                                allDay: false
                            });
                        }
                    }
                })
            }
            $(".list").click(function(){
                $(".list").css("backgroundColor", "#fff")
                $('#calendar').fullCalendar('removeEvents')
                var id = $(this).css("backgroundColor", "#eee").attr("id")
                $(":input[name=doctor_id]").val(id)
                var url = "/clerk/get_free_time/"+id
                $.getJSON(url, function(res){
                    if (res.code == 1) {
                        for(var i in res.data) {
                            var start = res.data[i]['start']['dateTime']
                            var end = res.data[i]['end']['dateTime']
                            var summary = res.data[i]['summary']
                            var eid = res.data[i]['id']
                            var bg = ''
                            if (summary == 'Free') {
                                bg = '#18d895'
                            }
                            if (summary == 'Booked') {
                                bg = '#EC4296'
                            }
                            $('#calendar').fullCalendar('renderEvent', {
                                title: summary,
                                start: start,
                                end: end,
                                id: eid,
                                backgroundColor: bg,
                                allDay: false
                            });
                        }
                    }
                })
            })
                
        })
    </script>
{% endblock %}

web/templates/clerk/statistics.html
{% extends "include/__layout.html" %}

{% block mybody %}
<div class="col-lg-12 grid-margin stretch-card">
  <canvas id="myChart" width="100%" height="40"></canvas>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.com/libraries/Chart.js"></script>
    <script>
        let d
        var bgs = [
          'rgba(255, 99, 132, 0.2)',
          'rgba(54, 162, 235, 0.2)',
          'rgba(255, 206, 86, 0.2)',
          'rgba(75, 192, 192, 0.2)',
          'rgba(153, 102, 255, 0.2)',
          'rgba(255, 159, 64, 0.2)'
        ];
        var bcs = [
          'rgba(255,99,132,1)',
          'rgba(54, 162, 235, 1)',
          'rgba(255, 206, 86, 1)',
          'rgba(75, 192, 192, 1)',
          'rgba(153, 102, 255, 1)',
          'rgba(255, 159, 64, 1)'
        ];
        $.getJSON('{{url_for("clerk.staJson")}}', function(data){
          d = data['data']
          var labels = d['labels']
          dataSets = []
          for(var i in d['appointments']) {
            colorIndex = parseInt(Math.random()*10%(bgs.length - 1))
            dataSets.push({
              "label": i,
              "data": d['appointments'][i],
              "backgroundColor" : bgs[colorIndex],
              "borderColor": bcs[colorIndex],
              "borderWidth": 1
            })
          }

          var ctx = document.getElementById("myChart");
          var myChart = new Chart(ctx, {
              type: 'line',
              data: {
                  labels: labels,
                  datasets: dataSets,
              },
              options: {
                  scales: {
                      yAxes: [{
                          ticks: {
                              beginAtZero:true
                          }
                      }]
                  }
              }
          });
        })
        
    </script>
{% endblock %}